api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
        html:
            mime_types: ['text/html']
            # The title of the API.
    title: 'API Escape games'
            # The description of the API.
    description: "Service web pour les applications légère de l'escape game"
    swagger:
        versions: [3]
