<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJcbt5Zx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJcbt5Zx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJcbt5Zx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJcbt5Zx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJcbt5Zx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jcbt5Zx',
    'container.build_id' => '13e7abb3',
    'container.build_time' => 1578470156,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJcbt5Zx');
